// Code generated by TestAlgType_ffi_wrapper_gen
#ifndef __TestAlgTypeCWrapper__
#define __TestAlgTypeCWrapper__

void hs_TestAlgType_init(void);

void hs_TestAlgType_end(void);


char*  f1_ffi_c(char* x1);
char*  f2_ffi_c(char* x1);
char*  f3_ffi_c(char* x1);

#endif
