-- Code generated by TestAlgType_ffi_wrapper_gen
{-# LANGUAGE ForeignFunctionInterface #-}

module TestAlgTypeFFIWrapper where

import Foreign.C.Types
import Foreign.C.String
import FFIGenerator.ShowToPerl
import Data.Map
import TestAlgType


foreign export ccall f1_ffi :: CString -> IO CString
foreign export ccall f2_ffi :: CString -> IO CString
foreign export ccall f3_ffi :: CString -> IO CString

f1_ffi :: CString -> IO CString
f1_ffi cstr = do
        str <- peekCString cstr
        let
            argtup :: AlgType
            argtup = read str
            x1 = argtup
            retval =  f1 x1
            retval_str = showToPerl $ show retval
        cstr' <- newCString retval_str
        return cstr'

f2_ffi :: CString -> IO CString
f2_ffi cstr = do
        str <- peekCString cstr
        let
            argtup :: Int
            argtup = read str
            x1 = argtup
            retval =  f2 x1
            retval_str = showToPerl $ show retval
        cstr' <- newCString retval_str
        return cstr'

f3_ffi :: CString -> IO CString
f3_ffi cstr = do
        str <- peekCString cstr
        let
            argtup :: AlgType
            argtup = read str
            x1 = argtup
            retval =  f3 x1
            retval_str = showToPerl $ show retval
        cstr' <- newCString retval_str
        return cstr'


