// Code generated by TestAlgType_ffi_wrapper_gen
#include <HsFFI.h>
#include "TestAlgTypeFFIWrapper_stub.h"
extern void __stginit_TestAlgTypeFFIWrapper(void);
#include <stdio.h>

void hs_TestAlgType_init(void){
    hs_init(0,0);
    hs_add_root(__stginit_TestAlgTypeFFIWrapper);
}

void hs_TestAlgType_end(void){
        hs_exit();
}

char*  f1_ffi_c(char* x1)
{
    char*  res = f1_ffi(x1);
    return res;
}

char*  f2_ffi_c(char* x1)
{
    char*  res = f2_ffi(x1);
    return res;
}

char*  f3_ffi_c(char* x1)
{
    char*  res = f3_ffi(x1);
    return res;
}

