// Code generated by ./test_AlgType.pl on Wed Feb 18 14:54:52 2015
#include "TestAlgTypeCWrapper.h"
int hs_begin(int n) {
    hs_TestAlgType_init();
    return n;
}

int hs_end(int n) {
    hs_TestAlgType_end();
    return n;
}

SV* f1_ser(char* sstr) {
    char* res = f1_ffi_c(sstr);
    SV* nres = newSVpv(res,0);
    return nres;
}

SV* f2_ser(char* sstr) {
    char* res = f2_ffi_c(sstr);
    SV* nres = newSVpv(res,0);
    return nres;
}

SV* f3_ser(char* sstr) {
    char* res = f3_ffi_c(sstr);
    SV* nres = newSVpv(res,0);
    return nres;
}
