import os

FC=os.environ.get('FC')

fsources = ['module_velfg_superkernel.f95', 'velfg_driver.f95']


#
# '-fopenmp','-mcmodel=medium',
FLFLAGS = ['-Ofast','-flto']
FLFLAGS += ['-fopenmp','-DWITH_OPENMP','-mcmodel=medium']
FFLAGS = FLFLAGS + ['-Wall','-cpp','-m64','-ffree-form','-ffree-line-length-0','-fconvert=little-endian','-frecord-marker=4']#, '-fopenmp']

# '-fopenmp','-mcmodel=medium',

envF=Environment(F95=FC,LINK=FC,LINKFLAGS=FLFLAGS,F95FLAGS=FFLAGS,F95PATH=['.' ,'/usr/local/include']) # LINKFLAGS=['-fopenmp'],

envF.Program('prog.exe',fsources,LIBS=['m'],LIBPATH=['.' ,'/usr/lib','/usr/local/lib'])

