// Code generated by F95StatementParser_ffi_wrapper_gen
#ifndef __F95StatementParserCWrapper__
#define __F95StatementParserCWrapper__

void hs_F95StatementParser_init(void);

void hs_F95StatementParser_end(void);


char*  parseF95Statement_ffi_c(char* x1);
char*  parseF95Decl_ffi_c(char* x1);

#endif
