// Code generated by test_F95StatementParser.pl on Sun Jul 10 12:49:07 2016
#include "F95StatementParserCWrapper.h"
int hs_begin(int n) {
    hs_F95StatementParser_init();
    return n;
}

int hs_end(int n) {
    hs_F95StatementParser_end();
    return n;
}

SV* parseF95Statement_ser(char* sstr) {
    char* res = parseF95Statement_ffi_c(sstr);
    SV* nres = newSVpv(res,0);
    return nres;
}

SV* parseF95Decl_ser(char* sstr) {
    char* res = parseF95Decl_ffi_c(sstr);
    SV* nres = newSVpv(res,0);
    return nres;
}
