// Code generated by F95StatementParser_ffi_wrapper_gen
#include <HsFFI.h>
#include "F95StatementParserFFIWrapper_stub.h"
extern void __stginit_F95StatementParserFFIWrapper(void);
#include <stdio.h>

void hs_F95StatementParser_init(void){
    hs_init(0,0);
    hs_add_root(__stginit_F95StatementParserFFIWrapper);
}

void hs_F95StatementParser_end(void){
        hs_exit();
}

char*  parseF95Statement_ffi_c(char* x1)
{
    char*  res = parseF95Statement_ffi(x1);
    return res;
}

char*  parseF95Decl_ffi_c(char* x1)
{
    char*  res = parseF95Decl_ffi(x1);
    return res;
}

