import os

FC=os.environ.get('FC')

print FC
fsources = ['refactored-source/cea2.f90','refactored-source/params_cea_inc.f90']

LDFLAGS= [] 
FFLAGS  = ['-cpp', '-Wall' ,'-Wno-character-truncation','-Wno-unused-label' ,'-Wno-unused-variable' ,'-Wno-unused-dummy-argument','-ffree-form', '-ffree-line-length-0','-fmax-stack-var-size=262144']#, '-fconvert=big-endian','-mcmodel=medium']

envF=Environment(FORTRAN=FC,F90=FC,LINK=FC,LINKFLAGS=LDFLAGS,F90FLAGS=FFLAGS,F90PATH=['.'])

envF.Program('cea2',fsources,LIBS=[],LIBPATH=['.'])
