import os

FC=os.environ.get('FC')

fsources = ['test_shapiro_dyn_update_superkernel.f95','module_shapiro_dyn_update_superkernel.f95','module_shapiro_dyn_update_superkernel_init.f95']

FFLAGS = ['-Wall','-cpp','-O3','-m64','-ffree-form','-ffree-line-length-0','-fconvert=little-endian','-frecord-marker=4']

envF=Environment(F95=FC,LINK=FC,F95FLAGS=FFLAGS,F95PATH=['.' ,'/usr/local/include'])

envF.Program('test_shapiro_dyn_update_superkernel',fsources,LIBS=['m'],LIBPATH=['.' ,'/usr/lib','/usr/local/lib'])

