module params_SIZE
      integer, parameter :: ldim=3
      integer, parameter :: lx1=8
      integer, parameter :: lxd=12
      integer, parameter :: lx2=lx1-2
      integer, parameter :: lelg=30*20*24
      integer, parameter :: lpmin=12
      integer, parameter :: lpmax=1024
      integer, parameter :: ldimt=1
      integer, parameter :: ldimt_proj=1
      integer, parameter :: lhis=1000
      integer, parameter :: maxobj=4
      integer, parameter :: lpert=1
      integer, parameter :: toteq=5
      integer, parameter :: nsessmax=2
      integer, parameter :: lxo=lx1
      integer, parameter :: mxprev=20
      integer, parameter :: lgmres=30
      integer, parameter :: lorder=3
      integer, parameter :: lx1m=lx1
      integer, parameter :: lfdm=0
      integer, parameter :: lelx=1
      integer, parameter :: lely=1
      integer, parameter :: lelz=1
      integer, parameter :: lelt=lelg/lpmin+3
      integer, parameter :: lbelt=1
      integer, parameter :: lpelt=1
      integer, parameter :: lcvelt=lelt


!module params_SIZE_inc
      integer, parameter :: lelv=lelt
      integer, parameter :: ly1=lx1
      integer, parameter :: lz1=1 +(ldim-2)*(lx1-1)
      integer, parameter :: lyd=lxd
      integer, parameter :: lzd=1 +(ldim-2)*(lxd-1)
      integer, parameter :: ly2=lx2
      integer, parameter :: lz2=1 +(ldim-2)*(lx2-1)
      integer, parameter :: ly1m=lx1m
      integer, parameter :: lz1m=1 +(ldim-2)*(lx1m-1)
      integer, parameter :: lp=lpmax
      integer, parameter :: ax1=lx1
      integer, parameter :: ay1=ax1
      integer, parameter :: az1=1 +(ldim-2)*(ax1-1)
      integer, parameter :: ax2=lx2
      integer, parameter :: ay2=ax2
      integer, parameter :: az2=1 +(ldim-2)*(ax2-1)
      integer, parameter :: lpelv=lpelt
      integer, parameter :: lpx1=lx1
      integer, parameter :: lpy1=lpx1
      integer, parameter :: lpz1=1 +(ldim-2)*(lpx1-1)
      integer, parameter :: lpx2=lx2
      integer, parameter :: lpy2=lpx2
      integer, parameter :: lpz2=1 +(ldim-2)*(lpx2-1)
      integer, parameter :: lbelv=lbelt
      integer, parameter :: lbx1=lx1
      integer, parameter :: lby1=lbx1
      integer, parameter :: lbz1=1 +(ldim-2)*(lbx1-1)
      integer, parameter :: lbx2=lx2
      integer, parameter :: lby2=lbx2
      integer, parameter :: lbz2=1 +(ldim-2)*(lbx2-1)
      integer, parameter :: lxz=lx1*lz1
      integer, parameter :: lzl=3 +2*(ldim-3)
      integer, parameter :: ldimt1=ldimt+1
      integer, parameter :: ldimt3=ldimt+3
      integer, parameter :: lx3=lx1
      integer, parameter :: ly3=ly1
      integer, parameter :: lz3=lz1
      integer, parameter :: lctmp0=2*lx1*ly1*lz1*lelt
      integer, parameter :: lctmp1=4*lx1*ly1*lz1*lelt
      integer, parameter :: maxmor=lelt
      integer, parameter :: lxs=1
      integer, parameter :: lys=lxs
      integer, parameter :: lzs=(lxs-1)*(ldim-2)+1
      integer, parameter :: maxmbr=lelt*6
      integer, parameter :: lcvx1=lx1
      integer, parameter :: lcvy1=lcvx1
      integer, parameter :: lcvz1=1 +(ldim-2)*(lcvx1-1)
      integer, parameter :: nmaxl_nn=min(1+(nsessmax-1)*2*ldim*lxz*lelt,2*ldim*lxz*lelt)
      integer, parameter :: nfldmax_nn=min(1+(nsessmax-1)*(ldim+1+ldimt),ldim+1+ldimt)
!end module params_SIZE_inc
end module params_SIZE
